# Colors (3024 Day)

[colors.bright]
black = '#5c5855'
blue = '#807d7c'
cyan = '#cdab53'
green = '#3a3432'
magenta = '#bcbbba'
red = '#dbaec3'
white = '#f7f7f7'
yellow = '#4a4543'

[colors.cursor]
cursor = '#4a4543'
text = '#f7f7f7'

[colors.normal]
black = '#090300'
blue = '#01a0e4'
cyan = '#8fbece'
green = '#01a252'
magenta = '#a16a94'
red = '#db2d20'
white = '#a5a2a2'
yellow = '#caba00'

[colors.primary]
background = '#f7f7f7'
foreground = '#4a4543'

[colors.selection]
background = '#a5a2a2'
text = '#4a4543'
