# Colors (Broadcast)

[colors.bright]
black = '#585858'
blue = '#9fcef0'
cyan = '#a0cef0'
green = '#83d182'
magenta = '#ffffff'
red = '#ff7b6b'
white = '#ffffff'
yellow = '#ffff7c'

[colors.cursor]
cursor = '#ffffff'
text = '#c0bbb6'

[colors.normal]
black = '#000000'
blue = '#6d9cbe'
cyan = '#6e9cbe'
green = '#519f50'
magenta = '#d0d0ff'
red = '#da4939'
white = '#ffffff'
yellow = '#ffd24a'

[colors.primary]
background = '#2b2b2b'
foreground = '#e6e1dc'

[colors.selection]
background = '#5a647e'
text = '#e6e1dc'
