# Colors (Builtin Tango Light)

[colors.bright]
black = '#555753'
blue = '#729fcf'
cyan = '#27d5d5'
green = '#7dd527'
magenta = '#ad7fa8'
red = '#ef2929'
white = '#eeeeec'
yellow = '#d6c329'

[colors.cursor]
cursor = '#000000'
text = '#ffffff'

[colors.normal]
black = '#000000'
blue = '#3465a4'
cyan = '#06989a'
green = '#4e9a06'
magenta = '#75507b'
red = '#cc0000'
white = '#babeb6'
yellow = '#c4a000'

[colors.primary]
background = '#ffffff'
foreground = '#000000'

[colors.selection]
background = '#b5d5ff'
text = '#000000'
