# Colors (Carbonfox)

[colors.bright]
black = '#484848'
blue = '#8cb6ff'
cyan = '#52bdff'
green = '#46c880'
magenta = '#c8a5ff'
red = '#f16da6'
white = '#e4e4e5'
yellow = '#2dc7c4'

[colors.cursor]
cursor = '#f2f4f8'
text = '#161616'

[colors.normal]
black = '#282828'
blue = '#78a9ff'
cyan = '#33b1ff'
green = '#25be6a'
magenta = '#be95ff'
red = '#ee5396'
white = '#dfdfe0'
yellow = '#08bdba'

[colors.primary]
background = '#161616'
foreground = '#f2f4f8'

[colors.selection]
background = '#2a2a2a'
text = '#f2f4f8'
