# Colors (Grass)

[colors.bright]
black = '#959595'
blue = '#0000bb'
cyan = '#55ffff'
green = '#00bb00'
magenta = '#ff55ff'
red = '#ff5959'
white = '#ffffff'
yellow = '#e7b000'

[colors.cursor]
cursor = '#d9744c'
text = '#ffffff'

[colors.normal]
black = '#000000'
blue = '#0000a3'
cyan = '#00bbbb'
green = '#00bb00'
magenta = '#ee59bb'
red = '#ff5959'
white = '#bbbbbb'
yellow = '#e7b000'

[colors.primary]
background = '#13773d'
foreground = '#fff0a5'

[colors.selection]
background = '#b64926'
text = '#ffffff'
