# Colors (Horizon Bright)

[colors.bright]
black = '#1a1c24'
blue = '#00c9e2'
cyan = '#00c7c3'
green = '#00cc7b'
magenta = '#ff6cba'
red = '#fe5f87'
white = '#fff2ef'
yellow = '#f1a383'

[colors.cursor]
cursor = '#dba69b'
text = '#f9cec3'

[colors.normal]
black = '#16161d'
blue = '#00bedd'
cyan = '#00c8c1'
green = '#00ce81'
magenta = '#ff58b1'
red = '#fc4777'
white = '#c3afac'
yellow = '#ffa27b'

[colors.primary]
background = '#fdf0ed'
foreground = '#16161d'

[colors.selection]
background = '#f9cec3'
text = '#16161d'
