# Colors (Hot Dog Stand)

[colors.bright]
black = '#000000'
blue = '#000000'
cyan = '#ffffff'
green = '#ffff54'
magenta = '#ffff54'
red = '#ffff54'
white = '#c6c6c6'
yellow = '#ffff54'

[colors.cursor]
cursor = '#ffff54'
text = '#b2b2b2'

[colors.normal]
black = '#000000'
blue = '#000000'
cyan = '#ffffff'
green = '#ffff54'
magenta = '#ffff54'
red = '#ffff54'
white = '#c6c6c6'
yellow = '#ffff54'

[colors.primary]
background = '#ea3323'
foreground = '#ffffff'

[colors.selection]
background = '#ffff54'
text = '#000000'
