# Colors (Man Page)

[colors.bright]
black = '#666666'
blue = '#0000ff'
cyan = '#00cbcb'
green = '#00cc00'
magenta = '#e500e5'
red = '#e50000'
white = '#e5e5e5'
yellow = '#bfbf00'

[colors.cursor]
cursor = '#7f7f7f'
text = '#000000'

[colors.normal]
black = '#000000'
blue = '#0000b2'
cyan = '#00a6b2'
green = '#00a600'
magenta = '#b200b2'
red = '#cc0000'
white = '#b2b2b2'
yellow = '#999900'

[colors.primary]
background = '#fef49c'
foreground = '#000000'

[colors.selection]
background = '#a4c9cd'
text = '#000000'
