# Colors (Pencil Light)

[colors.bright]
black = '#424242'
blue = '#20bbfc'
cyan = '#4fb8cc'
green = '#52caa2'
magenta = '#6855de'
red = '#fb007a'
white = '#f1f1f1'
yellow = '#c0b100'

[colors.cursor]
cursor = '#20bbfc'
text = '#424242'

[colors.normal]
black = '#212121'
blue = '#008ec4'
cyan = '#20a5ba'
green = '#10a778'
magenta = '#523c79'
red = '#c30771'
white = '#b3b3b3'
yellow = '#a89c14'

[colors.primary]
background = '#f1f1f1'
foreground = '#424242'

[colors.selection]
background = '#b6d6fd'
text = '#424242'
