# Colors (Tango Half Adapted)

[colors.bright]
black = '#797d76'
blue = '#76bfff'
cyan = '#00d0d4'
green = '#64d000'
magenta = '#d898d1'
red = '#ff0013'
white = '#f4f4f2'
yellow = '#d9c500'

[colors.cursor]
cursor = '#000000'
text = '#ffffff'

[colors.normal]
black = '#000000'
blue = '#008ef6'
cyan = '#00bdc3'
green = '#4cc300'
magenta = '#a96cb3'
red = '#ff0000'
white = '#babfb5'
yellow = '#e2c000'

[colors.primary]
background = '#ffffff'
foreground = '#000000'

[colors.selection]
background = '#c1deff'
text = '#000000'
