[colors]
background = '#f7f7f7'
foreground = '#4a4543'
selection-background = '#a5a2a2'
selection-foreground = '#4a4543'
cursor = '#4a4543'
black = '#090300'
red = '#db2d20'
green = '#01a252'
yellow = '#caba00'
blue = '#01a0e4'
magenta = '#a16a94'
cyan = '#8fbece'
white = '#a5a2a2'
light_black = '#5c5855'
light_red = '#dbaec3'
light_green = '#3a3432'
light_yellow = '#4a4543'
light_blue = '#807d7c'
light_magenta = '#bcbbba'
light_cyan = '#cdab53'
light_white = '#f7f7f7'
