[colors]
background = '#f8f9fa'
foreground = '#5c6166'
selection-background = '#035bd6'
selection-foreground = '#f8f9fa'
cursor = '#ffaa33'
black = '#000000'
red = '#ea6c6d'
green = '#6cbf43'
yellow = '#eca944'
blue = '#3199e1'
magenta = '#9e75c7'
cyan = '#46ba94'
white = '#c7c7c7'
light_black = '#686868'
light_red = '#f07171'
light_green = '#86b300'
light_yellow = '#f2ae49'
light_blue = '#399ee6'
light_magenta = '#a37acc'
light_cyan = '#4cbf99'
light_white = '#d1d1d1'
