[colors]
background = '#1f2430'
foreground = '#cccac2'
selection-background = '#409fff'
selection-foreground = '#1f2430'
cursor = '#ffcc66'
black = '#171b24'
red = '#ed8274'
green = '#87d96c'
yellow = '#facc6e'
blue = '#6dcbfa'
magenta = '#dabafa'
cyan = '#90e1c6'
white = '#c7c7c7'
light_black = '#686868'
light_red = '#f28779'
light_green = '#d5ff80'
light_yellow = '#ffd173'
light_blue = '#73d0ff'
light_magenta = '#dfbfff'
light_cyan = '#95e6cb'
light_white = '#ffffff'
