[colors]
background = '#ffffff'
foreground = '#000000'
selection-background = '#b5d5ff'
selection-foreground = '#000000'
cursor = '#000000'
black = '#000000'
red = '#cc0000'
green = '#4e9a06'
yellow = '#c4a000'
blue = '#3465a4'
magenta = '#75507b'
cyan = '#06989a'
white = '#babeb6'
light_black = '#555753'
light_red = '#ef2929'
light_green = '#7dd527'
light_yellow = '#d6c329'
light_blue = '#729fcf'
light_magenta = '#ad7fa8'
light_cyan = '#27d5d5'
light_white = '#eeeeec'
