[colors]
background = '#161616'
foreground = '#f2f4f8'
selection-background = '#2a2a2a'
selection-foreground = '#f2f4f8'
cursor = '#f2f4f8'
black = '#282828'
red = '#ee5396'
green = '#25be6a'
yellow = '#08bdba'
blue = '#78a9ff'
magenta = '#be95ff'
cyan = '#33b1ff'
white = '#dfdfe0'
light_black = '#484848'
light_red = '#f16da6'
light_green = '#46c880'
light_yellow = '#2dc7c4'
light_blue = '#8cb6ff'
light_magenta = '#c8a5ff'
light_cyan = '#52bdff'
light_white = '#e4e4e5'
