[colors]
background = '#f5deb3'
foreground = '#000000'
selection-background = '#c1deff'
selection-foreground = '#000000'
cursor = '#a1a1a1'
black = '#000000'
red = '#c91b00'
green = '#00c200'
yellow = '#aeab00'
blue = '#0225c7'
magenta = '#ca30c7'
cyan = '#00b9bb'
white = '#a1a1a1'
light_black = '#686868'
light_red = '#ff6e67'
light_green = '#20ba28'
light_yellow = '#b2af1b'
light_blue = '#6871ff'
light_magenta = '#f26af2'
light_cyan = '#20bdbf'
light_white = '#ffffff'
