[colors]
background = '#141414'
foreground = '#ffffff'
selection-background = '#303030'
selection-foreground = '#ffffff'
cursor = '#ffffff'
black = '#2a2a2a'
red = '#bf616a'
green = '#a3be8c'
yellow = '#ebcb8b'
blue = '#81a1c1'
magenta = '#b48ead'
cyan = '#88c0d0'
white = '#d8dee9'
light_black = '#505050'
light_red = '#bf616a'
light_green = '#a3be8c'
light_yellow = '#ebcb8b'
light_blue = '#81a1c1'
light_magenta = '#b48ead'
light_cyan = '#88c0d0'
light_white = '#ffffff'
