[colors]
background = '#070c0e'
foreground = '#3e5715'
selection-background = '#0f191c'
selection-foreground = '#00ff87'
cursor = '#9fa86e'
black = '#091013'
red = '#006536'
green = '#6fa64c'
yellow = '#7e8000'
blue = '#2c9a84'
magenta = '#523a60'
cyan = '#114d53'
white = '#006536'
light_black = '#404040'
light_red = '#00733d'
light_green = '#90d762'
light_yellow = '#e2e500'
light_blue = '#46d8b8'
light_magenta = '#573d66'
light_cyan = '#12545a'
light_white = '#006536'
