[colors]
background = '#070c0e'
foreground = '#35451a'
selection-background = '#0f191c'
selection-foreground = '#00ff87'
cursor = '#444733'
black = '#091013'
red = '#1a4831'
green = '#6fa64c'
yellow = '#595900'
blue = '#00cb6b'
magenta = '#4e375a'
cyan = '#125459'
white = '#1a4833'
light_black = '#404040'
light_red = '#0d452a'
light_green = '#90d762'
light_yellow = '#e2e500'
light_blue = '#00ff87'
light_magenta = '#4e375a'
light_cyan = '#176c73'
light_white = '#00381e'
