[colors]
background = '#faf4ed'
foreground = '#575279'
selection-background = '#d0d8d8'
selection-foreground = '#575279'
cursor = '#575279'
black = '#575279'
red = '#b4637a'
green = '#618774'
yellow = '#ea9d34'
blue = '#286983'
magenta = '#907aa9'
cyan = '#56949f'
white = '#b2b6bd'
light_black = '#5f5695'
light_red = '#c26d85'
light_green = '#629f81'
light_yellow = '#eea846'
light_blue = '#2d81a3'
light_magenta = '#9a80b9'
light_cyan = '#5ca7b4'
light_white = '#e6ebf3'
