[colors]
background = '#232136'
foreground = '#e0def4'
selection-background = '#433c59'
selection-foreground = '#e0def4'
cursor = '#e0def4'
black = '#393552'
red = '#eb6f92'
green = '#a3be8c'
yellow = '#f6c177'
blue = '#569fba'
magenta = '#c4a7e7'
cyan = '#9ccfd8'
white = '#e0def4'
light_black = '#47407d'
light_red = '#f083a2'
light_green = '#b1d196'
light_yellow = '#f9cb8c'
light_blue = '#65b1cd'
light_magenta = '#ccb1ed'
light_cyan = '#a6dae3'
light_white = '#e2e0f7'
