[colors]
background = '#f4f4f4'
foreground = '#3e3e3e'
selection-background = '#a9c1e2'
selection-foreground = '#535353'
cursor = '#3f3f3f'
black = '#3e3e3e'
red = '#970b16'
green = '#07962a'
yellow = '#c5bb94'
blue = '#003e8a'
magenta = '#e94691'
cyan = '#7cc4df'
white = '#b2b2b2'
light_black = '#666666'
light_red = '#de0000'
light_green = '#7ac895'
light_yellow = '#d7b600'
light_blue = '#2e6cba'
light_magenta = '#f29592'
light_cyan = '#00c7cb'
light_white = '#ffffff'
