[colors]
background = '#13773d'
foreground = '#fff0a5'
selection-background = '#b64926'
selection-foreground = '#ffffff'
cursor = '#d9744c'
black = '#000000'
red = '#ff5959'
green = '#00bb00'
yellow = '#e7b000'
blue = '#0000a3'
magenta = '#ee59bb'
cyan = '#00bbbb'
white = '#bbbbbb'
light_black = '#959595'
light_red = '#ff5959'
light_green = '#00bb00'
light_yellow = '#e7b000'
light_blue = '#0000bb'
light_magenta = '#ff55ff'
light_cyan = '#55ffff'
light_white = '#ffffff'
