[colors]
background = '#282828'
foreground = '#d4be98'
selection-background = '#d4be98'
selection-foreground = '#282828'
cursor = '#d4be98'
black = '#282828'
red = '#c14a4a'
green = '#6c782e'
yellow = '#b47109'
blue = '#45707a'
magenta = '#945e80'
cyan = '#4c7a5d'
white = '#d4be98'
light_black = '#7c6f64'
light_red = '#ea6962'
light_green = '#a9b665'
light_yellow = '#d8a657'
light_blue = '#7daea3'
light_magenta = '#d3869b'
light_cyan = '#89b482'
light_white = '#ddc7a1'
