[colors]
background = '#010515'
foreground = '#11b7ff'
selection-background = '#c1e4ff'
selection-foreground = '#a9a9a9'
cursor = '#10b6ff'
black = '#010921'
red = '#10b6ff'
green = '#10b6ff'
yellow = '#10b6ff'
blue = '#10b6ff'
magenta = '#10b6ff'
cyan = '#10b6ff'
white = '#fafafa'
light_black = '#484157'
light_red = '#00b3f7'
light_green = '#00b3f7'
light_yellow = '#00b3f7'
light_blue = '#00b3f7'
light_magenta = '#00b3f7'
light_cyan = '#00b3f7'
light_white = '#fefefe'
