[colors]
background = '#fdf0ed'
foreground = '#16161d'
selection-background = '#f9cec3'
selection-foreground = '#16161d'
cursor = '#dba69b'
black = '#16161d'
red = '#fc4777'
green = '#00ce81'
yellow = '#ffa27b'
blue = '#00bedd'
magenta = '#ff58b1'
cyan = '#00c8c1'
white = '#c3afac'
light_black = '#1a1c24'
light_red = '#fe5f87'
light_green = '#00cc7b'
light_yellow = '#f1a383'
light_blue = '#00c9e2'
light_magenta = '#ff6cba'
light_cyan = '#00c7c3'
light_white = '#fff2ef'
