[colors]
background = '#fdf0ed'
foreground = '#16161d'
selection-background = '#f9cec3'
selection-foreground = '#16161d'
cursor = '#d3a89d'
black = '#16161d'
red = '#fc4777'
green = '#00ca86'
yellow = '#f2a682'
blue = '#00bedd'
magenta = '#ff58b1'
cyan = '#00cdcb'
white = '#bfafac'
light_black = '#1a1c24'
light_red = '#fe5f87'
light_green = '#00d193'
light_yellow = '#e5a688'
light_blue = '#00c9e2'
light_magenta = '#ff6cba'
light_cyan = '#00c3c2'
light_white = '#fff2ef'
