[colors]
background = '#ffff54'
foreground = '#000000'
selection-background = '#ea3323'
selection-foreground = '#ffffff'
cursor = '#ea3323'
black = '#000000'
red = '#ea3323'
green = '#ea3323'
yellow = '#ea3323'
blue = '#000000'
magenta = '#ea3323'
cyan = '#000000'
white = '#c6c6c6'
light_black = '#000000'
light_red = '#ea3323'
light_green = '#ea3323'
light_yellow = '#ea3323'
light_blue = '#000000'
light_magenta = '#ea3323'
light_cyan = '#000000'
light_white = '#c6c6c6'
