[colors]
background = '#ea3323'
foreground = '#ffffff'
selection-background = '#ffff54'
selection-foreground = '#000000'
cursor = '#ffff54'
black = '#000000'
red = '#ffff54'
green = '#ffff54'
yellow = '#ffff54'
blue = '#000000'
magenta = '#ffff54'
cyan = '#ffffff'
white = '#c6c6c6'
light_black = '#000000'
light_red = '#ffff54'
light_green = '#ffff54'
light_yellow = '#ffff54'
light_blue = '#000000'
light_magenta = '#ffff54'
light_cyan = '#ffffff'
light_white = '#c6c6c6'
