[colors]
background = '#141414'
foreground = '#cecece'
selection-background = '#cecece'
selection-foreground = '#141414'
cursor = '#cecece'
black = '#141414'
red = '#d03333'
green = '#1bd01b'
yellow = '#d08c1b'
blue = '#1b1bd0'
magenta = '#d01bd0'
cyan = '#1bd0d0'
white = '#cecece'
light_black = '#4e4e4e'
light_red = '#dc4e4e'
light_green = '#4edc4e'
light_yellow = '#f3f34e'
light_blue = '#4e4edc'
light_magenta = '#f34ef3'
light_cyan = '#4ef3f3'
light_white = '#ffffff'
