[colors]
background = '#ffffff'
foreground = '#000000'
selection-background = '#c1deff'
selection-foreground = '#000000'
cursor = '#000000'
black = '#000000'
red = '#d81e00'
green = '#5ea702'
yellow = '#cfae00'
blue = '#427ab3'
magenta = '#89658e'
cyan = '#00a7aa'
white = '#b5b8b2'
light_black = '#686a66'
light_red = '#f54235'
light_green = '#8cd736'
light_yellow = '#d7c53a'
light_blue = '#84b0d8'
light_magenta = '#bc94b7'
light_cyan = '#1eccce'
light_white = '#f1f1f0'
