[colors]
background = '#2e2e2e'
foreground = '#ffffff'
selection-background = '#cb392e'
selection-foreground = '#ffffff'
cursor = '#7f7f7f'
black = '#2e2e2e'
red = '#fc6d26'
green = '#3eb383'
yellow = '#fca121'
blue = '#db3b21'
magenta = '#6b40a8'
cyan = '#6e49cb'
white = '#ffffff'
light_black = '#535353'
light_red = '#ff6517'
light_green = '#53eaa8'
light_yellow = '#fca013'
light_blue = '#db501f'
light_magenta = '#6a36b6'
light_cyan = '#7d53e7'
light_white = '#ffffff'
