[colors]
background = '#121212'
foreground = '#bebebe'
selection-background = '#333333'
selection-foreground = '#eaeaea'
cursor = '#eaeaea'
black = '#333333'
red = '#d35f5f'
green = '#ffc107'
yellow = '#b91c1c'
blue = '#e68e0d'
magenta = '#d35f5f'
cyan = '#bebebe'
white = '#bebebe'
light_black = '#8a8a8d'
light_red = '#891c1c'
light_green = '#ffc107'
light_yellow = '#b90a0a'
light_blue = '#f59e0b'
light_magenta = '#b91c1c'
light_cyan = '#eaeaea'
light_white = '#ffffff'
