[colors]
background = '#271f19'
foreground = '#ffffff'
selection-background = '#253b76'
selection-foreground = '#ffffff'
cursor = '#ffffff'
black = '#000000'
red = '#9a1a1a'
green = '#61ce3c'
yellow = '#fbde2d'
blue = '#324883'
magenta = '#ff0080'
cyan = '#8da6ce'
white = '#f8f8f8'
light_black = '#4c4c4c'
light_red = '#9a1a1a'
light_green = '#61ce3c'
light_yellow = '#fbde2d'
light_blue = '#324883'
light_magenta = '#ff0080'
light_cyan = '#8da6ce'
light_white = '#f8f8f8'
