[colors]
background = '#101010'
foreground = '#e0e1e4'
selection-background = '#696d79'
selection-foreground = '#e0e1e4'
cursor = '#e0e1e4'
black = '#151515'
red = '#b46958'
green = '#90a959'
yellow = '#f4bf75'
blue = '#bad7ff'
magenta = '#aa759f'
cyan = '#88afa2'
white = '#e1e1e1'
light_black = '#727272'
light_red = '#7e97ab'
light_green = '#90a959'
light_yellow = '#f4bf75'
light_blue = '#bad7ff'
light_magenta = '#aa759f'
light_cyan = '#88afa2'
light_white = '#afafaf'
