[colors]
background = '#e1e1e1'
foreground = '#151515'
selection-background = '#c6d5de'
selection-foreground = '#151515'
cursor = '#151515'
black = '#d6d6d6'
red = '#874e42'
green = '#677940'
yellow = '#b89058'
blue = '#8ba1bf'
magenta = '#aa759f'
cyan = '#3e5f66'
white = '#151515'
light_black = '#2b2b2b'
light_red = '#637786'
light_green = '#677940'
light_yellow = '#b89058'
light_blue = '#93a2ab'
light_magenta = '#aa759f'
light_cyan = '#99ab93'
light_white = '#373737'
