[colors]
background = '#2e3440'
foreground = '#cdcecf'
selection-background = '#3e4a5b'
selection-foreground = '#cdcecf'
cursor = '#cdcecf'
black = '#3b4252'
red = '#bf616a'
green = '#a3be8c'
yellow = '#ebcb8b'
blue = '#81a1c1'
magenta = '#b48ead'
cyan = '#88c0d0'
white = '#e5e9f0'
light_black = '#53648d'
light_red = '#d06f79'
light_green = '#b1d196'
light_yellow = '#f0d399'
light_blue = '#8cafd2'
light_magenta = '#c895bf'
light_cyan = '#93ccdc'
light_white = '#e7ecf4'
