[colors]
background = '#e5e9f0'
foreground = '#414858'
selection-background = '#d8dee9'
selection-foreground = '#4c556a'
cursor = '#7bb3c3'
black = '#3b4252'
red = '#bf616a'
green = '#96b17f'
yellow = '#c5a565'
blue = '#81a1c1'
magenta = '#b48ead'
cyan = '#7bb3c3'
white = '#a5abb6'
light_black = '#4c566a'
light_red = '#bf616a'
light_green = '#96b17f'
light_yellow = '#c5a565'
light_blue = '#81a1c1'
light_magenta = '#b48ead'
light_cyan = '#82afae'
light_white = '#eceff4'
