[colors]
background = '#224fbc'
foreground = '#ffffff'
selection-background = '#216dff'
selection-foreground = '#ffffff'
cursor = '#7f7f7f'
black = '#000000'
red = '#e64c4c'
green = '#00a600'
yellow = '#999900'
blue = '#0000b2'
magenta = '#d826d8'
cyan = '#00a6b2'
white = '#bfbfbf'
light_black = '#808080'
light_red = '#ff1a1a'
light_green = '#00d900'
light_yellow = '#e5e500'
light_blue = '#7373ff'
light_magenta = '#e500e5'
light_cyan = '#00e5e5'
light_white = '#e5e5e5'
