[colors]
background = '#212121'
foreground = '#f1f1f1'
selection-background = '#b6d6fd'
selection-foreground = '#989898'
cursor = '#20bbfc'
black = '#212121'
red = '#c30771'
green = '#10a778'
yellow = '#a89c14'
blue = '#008ec4'
magenta = '#5f4986'
cyan = '#20a5ba'
white = '#d9d9d9'
light_black = '#4f4f4f'
light_red = '#fb007a'
light_green = '#5fd7af'
light_yellow = '#f3e430'
light_blue = '#20bbfc'
light_magenta = '#6855de'
light_cyan = '#4fb8cc'
light_white = '#f1f1f1'
