[colors]
background = '#052454'
foreground = '#f6f6f7'
selection-background = '#f6f6f7'
selection-foreground = '#052454'
cursor = '#f6f6f7'
black = '#000000'
red = '#981a22'
green = '#098003'
yellow = '#c4a000'
blue = '#4140c3'
magenta = '#d33682'
cyan = '#0e807f'
white = '#7f7c7f'
light_black = '#808080'
light_red = '#ef2929'
light_green = '#1cfe3c'
light_yellow = '#fefe45'
light_blue = '#268ad2'
light_magenta = '#fe13fa'
light_cyan = '#29fffe'
light_white = '#c2c1c3'
