[colors]
background = '#ffffff'
foreground = '#191919'
selection-background = '#c1ddff'
selection-foreground = '#191919'
cursor = '#4d4d4d'
black = '#000000'
red = '#e5492b'
green = '#50d148'
yellow = '#c6c440'
blue = '#3b75ff'
magenta = '#ed66e8'
cyan = '#4ed2de'
white = '#c2c2c2'
light_black = '#9f9f9f'
light_red = '#ff6640'
light_green = '#48d53e'
light_yellow = '#bfbe23'
light_blue = '#0082ff'
light_magenta = '#ff7eff'
light_cyan = '#3bd1d2'
light_white = '#f2f2f2'
