[colors]
background = '#1a1a1a'
foreground = '#ffffff'
selection-background = '#333333'
selection-foreground = '#595959'
cursor = '#cccccc'
black = '#000000'
red = '#ff5360'
green = '#59d499'
yellow = '#ffc531'
blue = '#56c2ff'
magenta = '#cf2f98'
cyan = '#52eee5'
white = '#ffffff'
light_black = '#4c4c4c'
light_red = '#ff6363'
light_green = '#59d499'
light_yellow = '#ffc531'
light_blue = '#56c2ff'
light_magenta = '#cf2f98'
light_cyan = '#52eee5'
light_white = '#ffffff'
