[colors]
background = '#ffffff'
foreground = '#000000'
selection-background = '#c1deff'
selection-foreground = '#000000'
cursor = '#000000'
black = '#000000'
red = '#ff0000'
green = '#4cc300'
yellow = '#e2c000'
blue = '#008ef6'
magenta = '#a96cb3'
cyan = '#00bdc3'
white = '#babfb5'
light_black = '#797d76'
light_red = '#ff0013'
light_green = '#70dc00'
light_yellow = '#d9c600'
light_blue = '#76bfff'
light_magenta = '#d898d1'
light_cyan = '#00d0d4'
light_white = '#f4f4f2'
