[colors]
background = '#f8f8ff'
foreground = '#1d1d26'
selection-background = '#ff3399'
selection-foreground = '#ffffff'
cursor = '#b1b1d6'
black = '#1d1d26'
red = '#ff3399'
green = '#00d364'
yellow = '#e5b24d'
blue = '#00cbff'
magenta = '#cc66ff'
cyan = '#00ceca'
white = '#b1b1d6'
light_black = '#636667'
light_red = '#ff2f92'
light_green = '#00d364'
light_yellow = '#d9ae53'
light_blue = '#00cbff'
light_magenta = '#d783ff'
light_cyan = '#00c8c7'
light_white = '#d5d6f3'
