[colors]
background = '#ff8cd9'
foreground = '#0b0b0b'
selection-background = '#3ea9fe'
selection-foreground = '#ffffff'
cursor = '#c7ff98'
black = '#0c0c0c'
red = '#a80f20'
green = '#c7ff98'
yellow = '#fff964'
blue = '#145fcd'
magenta = '#ffe9ff'
cyan = '#9effef'
white = '#fcf1fb'
light_black = '#434343'
light_red = '#d91329'
light_green = '#d3ffaf'
light_yellow = '#ffef50'
light_blue = '#0075ea'
light_magenta = '#ffefff'
light_cyan = '#93ffef'
light_white = '#fff3fe'
