[colors]
background = '#101010'
foreground = '#fafafa'
selection-background = '#005be7'
selection-foreground = '#fafafa'
cursor = '#f32882'
black = '#000000'
red = '#fc0036'
green = '#29a948'
yellow = '#ffae00'
blue = '#006aff'
magenta = '#f32882'
cyan = '#00ac96'
white = '#feffff'
light_black = '#a8a8a8'
light_red = '#ff8080'
light_green = '#4be15d'
light_yellow = '#ffae00'
light_blue = '#49aeff'
light_magenta = '#f97ea8'
light_cyan = '#00e4c4'
light_white = '#fefefe'
