[colors]
background = '#3f3f3f'
foreground = '#dcdccc'
selection-background = '#21322f'
selection-foreground = '#c2d87a'
cursor = '#73635a'
black = '#4d4d4d'
red = '#7d5d5d'
green = '#60b48a'
yellow = '#f0dfaf'
blue = '#5d6d7d'
magenta = '#dc8cc3'
cyan = '#8cd0d3'
white = '#dcdccc'
light_black = '#709080'
light_red = '#dca3a3'
light_green = '#c3bf9f'
light_yellow = '#e0cf9f'
light_blue = '#94bff3'
light_magenta = '#ec93d3'
light_cyan = '#93e0e3'
light_white = '#ffffff'
