# Aurora
[colors]
foreground = "#ffca28"
background = "#23262e"
cursor_bg = "#ee5d43"
cursor_border = "#ee5d43"
cursor_fg = "#ffd29c"
selection_bg = "#292e38"
selection_fg = "#00e8c6"

ansi = ["#23262e","#f0266f","#8fd46d","#ffe66d","#102ee4","#ee5d43","#03d6b8","#c74ded"]
brights = ["#4f545e","#f92672","#8fd46d","#ffe66d","#03d6b8","#ee5d43","#03d6b8","#c74ded"]
