# Ayu Light
[colors]
foreground = "#5c6166"
background = "#f8f9fa"
cursor_bg = "#ffaa33"
cursor_border = "#ffaa33"
cursor_fg = "#f8f9fa"
selection_bg = "#035bd6"
selection_fg = "#f8f9fa"

ansi = ["#000000","#ea6c6d","#6cbf43","#eca944","#3199e1","#9e75c7","#46ba94","#bababa"]
brights = ["#686868","#f07171","#86b300","#f2ae49","#399ee6","#a37acc","#4cbf99","#d1d1d1"]
