# Black Metal (Mayhem)
[colors]
foreground = "#c1c1c1"
background = "#000000"
cursor_bg = "#c1c1c1"
cursor_border = "#c1c1c1"
cursor_fg = "#8e8e8e"
selection_bg = "#c1c1c1"
selection_fg = "#000000"

ansi = ["#000000","#5f8787","#f3ecd4","#eecc6c","#888888","#999999","#aaaaaa","#c1c1c1"]
brights = ["#404040","#5f8787","#f3ecd4","#eecc6c","#888888","#999999","#aaaaaa","#c1c1c1"]
