# Black Metal (Venom)
[colors]
foreground = "#c1c1c1"
background = "#000000"
cursor_bg = "#c1c1c1"
cursor_border = "#c1c1c1"
cursor_fg = "#c1c1c1"
selection_bg = "#c1c1c1"
selection_fg = "#000000"

ansi = ["#000000","#5f8787","#f8f7f2","#79241f","#888888","#999999","#aaaaaa","#c1c1c1"]
brights = ["#3f3f3f","#5f8787","#f8f7f2","#79241f","#888888","#999999","#aaaaaa","#c1c1c1"]
