# Builtin Tango Light
[colors]
foreground = "#000000"
background = "#ffffff"
cursor_bg = "#000000"
cursor_border = "#000000"
cursor_fg = "#ffffff"
selection_bg = "#b5d5ff"
selection_fg = "#000000"

ansi = ["#000000","#cc0000","#4e9a06","#c4a000","#3465a4","#75507b","#06989a","#babeb6"]
brights = ["#555753","#ef2929","#7dd527","#d6c329","#729fcf","#ad7fa8","#27d5d5","#eeeeec"]
