# Carbonfox
[colors]
foreground = "#f2f4f8"
background = "#161616"
cursor_bg = "#f2f4f8"
cursor_border = "#f2f4f8"
cursor_fg = "#161616"
selection_bg = "#2a2a2a"
selection_fg = "#f2f4f8"

ansi = ["#282828","#ee5396","#25be6a","#08bdba","#78a9ff","#be95ff","#33b1ff","#dfdfe0"]
brights = ["#484848","#f16da6","#46c880","#2dc7c4","#8cb6ff","#c8a5ff","#52bdff","#e4e4e5"]
