# Fahrenheit
[colors]
foreground = "#ffffce"
background = "#000000"
cursor_bg = "#bbbbbb"
cursor_border = "#bbbbbb"
cursor_fg = "#ffffff"
selection_bg = "#4e739f"
selection_fg = "#ffffce"

ansi = ["#1d1d1d","#cda074","#9e744d","#fecf75","#7f0e0f","#734c4d","#979797","#ffffce"]
brights = ["#404040","#fecea0","#cc734d","#fd9f4d","#cb4a05","#4e739f","#fed04d","#ffffff"]
