# GitHub
[colors]
foreground = "#3e3e3e"
background = "#f4f4f4"
cursor_bg = "#3f3f3f"
cursor_border = "#3f3f3f"
cursor_fg = "#f4f4f4"
selection_bg = "#a9c1e2"
selection_fg = "#535353"

ansi = ["#3e3e3e","#970b16","#07962a","#c5bb94","#003e8a","#e94691","#7cc4df","#b2b2b2"]
brights = ["#666666","#de0000","#7ac895","#d7b600","#2e6cba","#f29592","#00c7cb","#ffffff"]
