# Grass
[colors]
foreground = "#fff0a5"
background = "#13773d"
cursor_bg = "#d9744c"
cursor_border = "#d9744c"
cursor_fg = "#ffffff"
selection_bg = "#b64926"
selection_fg = "#ffffff"

ansi = ["#000000","#ff5959","#00bb00","#e7b000","#0000a3","#ee59bb","#00bbbb","#bbbbbb"]
brights = ["#959595","#ff5959","#00bb00","#e7b000","#0000bb","#ff55ff","#55ffff","#ffffff"]
