# Havn Daggry
[colors]
foreground = "#3b4a7a"
background = "#f8f9fb"
cursor_bg = "#226c4f"
cursor_border = "#226c4f"
cursor_fg = "#d6dbeb"
selection_bg = "#cfe9dd"
selection_fg = "#313c64"

ansi = ["#1f2842","#985248","#577159","#be6b00","#3a577d","#7c5c97","#925780","#b0b5c5"]
brights = ["#1f2842","#cc4a35","#719679","#f1a527","#6089c0","#7d7396","#aa869d","#d6dbeb"]
