# HaX0R Gr33N
[colors]
foreground = "#16b10e"
background = "#020f01"
cursor_bg = "#15d00d"
cursor_border = "#15d00d"
cursor_fg = "#ffffff"
selection_bg = "#d4ffc1"
selection_fg = "#b0b0b0"

ansi = ["#001f0b","#15d00d","#15d00d","#15d00d","#15d00d","#15d00d","#15d00d","#fafafa"]
brights = ["#334843","#19e20e","#19e20e","#19e20e","#19e20e","#19e20e","#19e20e","#fefefe"]
