# HaX0R Blue
[colors]
foreground = "#11b7ff"
background = "#010515"
cursor_bg = "#10b6ff"
cursor_border = "#10b6ff"
cursor_fg = "#ffffff"
selection_bg = "#c1e4ff"
selection_fg = "#a9a9a9"

ansi = ["#010921","#10b6ff","#10b6ff","#10b6ff","#10b6ff","#10b6ff","#10b6ff","#fafafa"]
brights = ["#484157","#00b3f7","#00b3f7","#00b3f7","#00b3f7","#00b3f7","#00b3f7","#fefefe"]
