# Horizon Bright
[colors]
foreground = "#16161d"
background = "#fdf0ed"
cursor_bg = "#d3a89d"
cursor_border = "#d3a89d"
cursor_fg = "#ffe8dc"
selection_bg = "#f9cec3"
selection_fg = "#16161d"

ansi = ["#16161d","#fc4777","#00ca86","#f2a682","#00bedd","#ff58b1","#00cdcb","#bfafac"]
brights = ["#1a1c24","#fe5f87","#00d193","#e5a688","#00c9e2","#ff6cba","#00c3c2","#fff2ef"]
