# iTerm2 Tango Light
[colors]
foreground = "#000000"
background = "#ffffff"
cursor_bg = "#000000"
cursor_border = "#000000"
cursor_fg = "#ffffff"
selection_bg = "#c1deff"
selection_fg = "#000000"

ansi = ["#000000","#d81e00","#5ea702","#cfae00","#427ab3","#89658e","#00a7aa","#c1c4be"]
brights = ["#686a66","#f54235","#8cd636","#d7c53b","#84b0d8","#bc94b7","#1eccce","#f1f1f0"]
