# Matte Black
[colors]
foreground = "#bebebe"
background = "#121212"
cursor_bg = "#eaeaea"
cursor_border = "#eaeaea"
cursor_fg = "#121212"
selection_bg = "#333333"
selection_fg = "#eaeaea"

ansi = ["#333333","#d35f5f","#ffc107","#b91c1c","#e68e0d","#d35f5f","#bebebe","#bebebe"]
brights = ["#8a8a8d","#891c1c","#ffc107","#b90a0a","#f59e0b","#b91c1c","#eaeaea","#ffffff"]
