# No Clown Fiesta
[colors]
foreground = "#e0e1e4"
background = "#101010"
cursor_bg = "#e0e1e4"
cursor_border = "#e0e1e4"
cursor_fg = "#18191b"
selection_bg = "#696d79"
selection_fg = "#e0e1e4"

ansi = ["#151515","#b46958","#90a959","#f4bf75","#bad7ff","#aa759f","#88afa2","#e1e1e1"]
brights = ["#727272","#7e97ab","#90a959","#f4bf75","#bad7ff","#aa759f","#88afa2","#afafaf"]
