# Nord Light
[colors]
foreground = "#414858"
background = "#e5e9f0"
cursor_bg = "#7bb3c3"
cursor_border = "#7bb3c3"
cursor_fg = "#3b4252"
selection_bg = "#d8dee9"
selection_fg = "#4c556a"

ansi = ["#3b4252","#bf616a","#96b17f","#c5a565","#81a1c1","#b48ead","#7bb3c3","#a5abb6"]
brights = ["#4c566a","#bf616a","#96b17f","#c5a565","#81a1c1","#b48ead","#82afae","#eceff4"]
