# Obsidian
[colors]
foreground = "#cdcdcd"
background = "#283033"
cursor_bg = "#c0cad0"
cursor_border = "#c0cad0"
cursor_fg = "#8d8d8d"
selection_bg = "#3e4c4f"
selection_fg = "#dfe1e2"

ansi = ["#000000","#b30d0e","#00bb00","#fecd22","#3a9bdb","#bb00bb","#00bbbb","#bbbbbb"]
brights = ["#555555","#ff0003","#93c863","#fef874","#a1d7ff","#ff55ff","#55ffff","#ffffff"]
