# Ocean
[colors]
foreground = "#ffffff"
background = "#224fbc"
cursor_bg = "#7f7f7f"
cursor_border = "#7f7f7f"
cursor_fg = "#ffffff"
selection_bg = "#216dff"
selection_fg = "#ffffff"

ansi = ["#000000","#e64c4c","#00a600","#999900","#0000b2","#d826d8","#00a6b2","#bfbfbf"]
brights = ["#808080","#ff1a1a","#00d900","#e5e500","#7373ff","#e500e5","#00e5e5","#e5e5e5"]
