# One Half Light
[colors]
foreground = "#383a42"
background = "#fafafa"
cursor_bg = "#a5b5e5"
cursor_border = "#a5b5e5"
cursor_fg = "#383a42"
selection_bg = "#bfceff"
selection_fg = "#383a42"

ansi = ["#383a42","#e45649","#50a14f","#c18401","#0184bc","#a626a4","#0997b3","#bababa"]
brights = ["#4f525e","#e06c75","#98c379","#d8b36e","#61afef","#c678dd","#56b6c2","#ffffff"]
