# Pencil Dark
[colors]
foreground = "#f1f1f1"
background = "#212121"
cursor_bg = "#20bbfc"
cursor_border = "#20bbfc"
cursor_fg = "#f1f1f1"
selection_bg = "#b6d6fd"
selection_fg = "#989898"

ansi = ["#212121","#c30771","#10a778","#a89c14","#008ec4","#5f4986","#20a5ba","#d9d9d9"]
brights = ["#4f4f4f","#fb007a","#5fd7af","#f3e430","#20bbfc","#6855de","#4fb8cc","#f1f1f1"]
