# Pro Light
[colors]
foreground = "#191919"
background = "#ffffff"
cursor_bg = "#4d4d4d"
cursor_border = "#4d4d4d"
cursor_fg = "#f2f2f2"
selection_bg = "#c1ddff"
selection_fg = "#191919"

ansi = ["#000000","#e5492b","#50d148","#c6c440","#3b75ff","#ed66e8","#4ed2de","#c2c2c2"]
brights = ["#9f9f9f","#ff6640","#48d53e","#bfbe23","#0082ff","#ff7eff","#3bd1d2","#f2f2f2"]
