# Raycast Dark
[colors]
foreground = "#ffffff"
background = "#1a1a1a"
cursor_bg = "#cccccc"
cursor_border = "#cccccc"
cursor_fg = "#999999"
selection_bg = "#333333"
selection_fg = "#595959"

ansi = ["#000000","#ff5360","#59d499","#ffc531","#56c2ff","#cf2f98","#52eee5","#ffffff"]
brights = ["#4c4c4c","#ff6363","#59d499","#ffc531","#56c2ff","#cf2f98","#52eee5","#ffffff"]
