# Sugarplum
[colors]
foreground = "#db7ddd"
background = "#111147"
cursor_bg = "#53b397"
cursor_border = "#53b397"
cursor_fg = "#93f3d7"
selection_bg = "#5ca8dc"
selection_fg = "#ead8ff"

ansi = ["#111147","#5ca8dc","#53b397","#249a84","#db7ddd","#d0beee","#f9f3f9","#a175d4"]
brights = ["#44447a","#5cb5dc","#52deb5","#01f5c7","#fa5dfd","#c6a5fd","#ffffff","#b577fd"]
