# Tango Half Adapted
[colors]
foreground = "#000000"
background = "#ffffff"
cursor_bg = "#000000"
cursor_border = "#000000"
cursor_fg = "#ffffff"
selection_bg = "#c1deff"
selection_fg = "#000000"

ansi = ["#000000","#ff0000","#4cc300","#e2c000","#008ef6","#a96cb3","#00bdc3","#babfb5"]
brights = ["#797d76","#ff0013","#64d000","#d9c500","#76bfff","#d898d1","#00d0d4","#f4f4f2"]
