# Tango Adapted
[colors]
foreground = "#000000"
background = "#ffffff"
cursor_bg = "#000000"
cursor_border = "#000000"
cursor_fg = "#ffffff"
selection_bg = "#c1deff"
selection_fg = "#000000"

ansi = ["#000000","#ff0000","#59d600","#e3be00","#00a2ff","#c17ecc","#00d0d6","#c0c4bb"]
brights = ["#8f928b","#ff0013","#6dd800","#ccbe00","#88c9ff","#e9a7e1","#00d7d9","#f6f6f4"]
