# Tinacious Design Light
[colors]
foreground = "#1d1d26"
background = "#f8f8ff"
cursor_bg = "#b2b2d7"
cursor_border = "#b2b2d7"
cursor_fg = "#ffffff"
selection_bg = "#ff3399"
selection_fg = "#ffffff"

ansi = ["#1d1d26","#ff3399","#00d364","#e5b34d","#00cbff","#cc66ff","#00ceca","#b2b2d7"]
brights = ["#636667","#ff2f92","#00d364","#d9ae52","#00cbff","#d783ff","#00c8c7","#d5d6f3"]
