# Vercel
[colors]
foreground = "#fafafa"
background = "#101010"
cursor_bg = "#f32882"
cursor_border = "#f32882"
cursor_fg = "#fafafa"
selection_bg = "#005be7"
selection_fg = "#fafafa"

ansi = ["#000000","#fc0036","#29a948","#ffae00","#006aff","#f32882","#00ac96","#feffff"]
brights = ["#a8a8a8","#ff8080","#4be15d","#ffae00","#49aeff","#f97ea8","#00e4c4","#fefefe"]
