tags = ["light"]

[theme.colors]
background = "#f5deb3"
foreground = "#000000"
bright-foreground = "#00c200"

[theme.colors.palette]
0 = "#000000"
1 = "#c91b00"
2 = "#00c200"
3 = "#aeab00"
4 = "#0225c7"
5 = "#ca30c7"
6 = "#00b9bb"
7 = "#a1a1a1"
8 = "#686868"
9 = "#ff6e67"
10 = "#20ba28"
11 = "#b2af1b"
12 = "#6871ff"
13 = "#f26af2"
14 = "#20bdbf"
15 = "#ffffff"
