tags = ["light"]

[theme.colors]
background = "#fdf0ed"
foreground = "#16161d"
bright-foreground = "#16161d"

[theme.colors.palette]
0 = "#16161d"
1 = "#fc4777"
2 = "#00ce81"
3 = "#ffa27b"
4 = "#00bedd"
5 = "#ff58b1"
6 = "#00c8c1"
7 = "#c3afac"
8 = "#1a1c24"
9 = "#fe5f87"
10 = "#00cc7b"
11 = "#f1a383"
12 = "#00c9e2"
13 = "#ff6cba"
14 = "#00c7c3"
15 = "#fff2ef"
