tags = ["light"]

[theme.colors]
background = "#ffffff"
foreground = "#191919"
bright-foreground = "#191919"

[theme.colors.palette]
0 = "#000000"
1 = "#e5492b"
2 = "#50d148"
3 = "#c6c440"
4 = "#3b75ff"
5 = "#ed66e8"
6 = "#4ed2de"
7 = "#c3c3c3"
8 = "#9f9f9f"
9 = "#ff6640"
10 = "#48d53d"
11 = "#bfbe23"
12 = "#0082ff"
13 = "#ff7eff"
14 = "#3ad0d2"
15 = "#f2f2f2"
